
[functions.mailer]
enabled = true
verify_jwt = true
import_map = "./functions/mailer/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mailer/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mailer/*.html" ]

[functions.auth-reset]
enabled = true
verify_jwt = true
import_map = "./functions/auth-reset/deno.json"
entrypoint = "./functions/auth-reset/index.ts"
