/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xdqiairmairmnrbqvawr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcWlhaXJtYWlybW5yYnF2YXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDUxNzYsImV4cCI6MjA3MjMyMTE3Nn0.7EEx6FpEaeEX2_Ac--7Z1oF0HzJKYcCyMZanvbF1xII"